# Generated by Django 4.2.26 on 2025-11-16 14:55

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('super_admin', '超级管理员'), ('operator', '运营管理员'), ('devops', '运维管理员')], default='operator', help_text='管理员角色（超级管理员/运营管理员/运维管理员）', max_length=20, verbose_name='角色')),
                ('real_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('status', models.CharField(choices=[('active', '正常'), ('disabled', '禁用'), ('locked', '锁定')], default='active', max_length=20, verbose_name='账号状态')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('login_fail_count', models.IntegerField(default=0, verbose_name='连续登录失败次数')),
                ('lock_until', models.DateTimeField(blank=True, null=True, verbose_name='锁定截止时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', null=True)),
                ('session_key', models.CharField(default=None, max_length=256, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='usermodel_set', related_query_name='usermodel', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usermodel_set', related_query_name='usermodel', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'db_table': 'user',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('login_status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20, verbose_name='登录状态')),
                ('fail_reason', models.CharField(blank=True, choices=[('invalid_username', '用户名不存在'), ('invalid_password', '密码错误'), ('account_disabled', '账号已禁用'), ('account_locked', '账号已锁定'), ('too_many_attempts', '登录尝试次数过多'), ('other', '其他原因')], max_length=50, null=True, verbose_name='失败原因')),
                ('ip_address', models.GenericIPAddressField(verbose_name='登录IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='地理位置')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'login_logs',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', '-login_time'], name='login_logs_user_id_6485c0_idx'), models.Index(fields=['username', '-login_time'], name='login_logs_usernam_061187_idx'), models.Index(fields=['login_status', '-login_time'], name='login_logs_login_s_5906cb_idx')],
            },
        ),
    ]
