#!/bin/bash

# 🚀 AI交易系统一键启动脚本
# 请在3个不同的终端窗口中分别运行以下命令

echo "=========================================="
echo "🤖 AI自动交易系统启动指南"
echo "=========================================="
echo ""
echo "请按照以下步骤在不同终端中启动服务："
echo ""
echo "📍 终端 1: Django API 服务器"
echo "-------------------------------------------"
echo "cd /workspace/code/Trade/server"
echo "python manage.py runserver 0.0.0.0:8000"
echo ""
echo "📍 终端 2: AI 智能体（自动交易引擎）"
echo "-------------------------------------------"
echo "cd /workspace/code/Trade/server"
echo "./start_all_agents.sh"
echo ""
echo "   这会启动5个智能体："
echo "   ✅ 感知层 - 每30秒监控市场"
echo "   ✅ 决策层 - 每60秒AI决策"
echo "   ✅ 执行层 - 每30秒自动交易"
echo "   ✅ 规划层 - 每5分钟制定计划"
echo "   ✅ 反思层 - 每小时自动学习"
echo ""
echo "📍 终端 3: 前端监控界面"
echo "-------------------------------------------"
echo "cd /workspace/code/Trade/web"
echo "npm run dev"
echo ""
echo "然后访问: http://localhost:3000"
echo ""
echo "=========================================="
echo "📊 监控运行状态"
echo "=========================================="
echo ""
echo "查看智能体实时日志:"
echo "  tail -f /workspace/code/Trade/server/logs/*.log"
echo ""
echo "停止所有智能体:"
echo "  cd /workspace/code/Trade/server"
echo "  ./stop_all_agents.sh"
echo ""
echo "=========================================="
echo "⚠️  重要说明"
echo "=========================================="
echo ""
echo "✅ 当前运行在【模拟交易模式】"
echo "✅ 不会真实买卖股票"
echo "✅ 使用虚拟资金（初始100万）"
echo "✅ 所有交易在数据库中记录"
echo ""
echo "📝 配置OpenAI API Key（可选，用于AI决策）:"
echo "   编辑 server/core/settings.py"
echo "   设置 OPENAI_API_KEY = 'your-key'"
echo ""
echo "=========================================="
echo "🎉 系统启动后将自动运行！"
echo "=========================================="

