# Generated by Django 4.2.26 on 2025-11-22 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('perception', '感知层'), ('memory', '记忆层'), ('planning', '规划层'), ('decision', '决策层'), ('execution', '执行层'), ('reflection', '反思层')], max_length=20, unique=True, verbose_name='智能体类型')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止'), ('error', '错误'), ('paused', '已暂停')], default='stopped', max_length=20, verbose_name='状态')),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
                ('last_action', models.CharField(blank=True, max_length=500, null=True, verbose_name='最后操作')),
                ('current_task', models.TextField(blank=True, null=True, verbose_name='当前任务')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='性能指标')),
                ('error_count', models.IntegerField(default=0, verbose_name='错误次数')),
                ('last_error', models.TextField(blank=True, null=True, verbose_name='最后错误')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '智能体状态',
                'verbose_name_plural': '智能体状态',
                'db_table': 'agent_status',
            },
        ),
        migrations.CreateModel(
            name='DecisionRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, verbose_name='标的代码')),
                ('decision_type', models.CharField(choices=[('buy', '买入'), ('sell', '卖出'), ('hold', '持有'), ('adjust', '调整'), ('abandon', '放弃')], max_length=20, verbose_name='决策类型')),
                ('decision_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='决策时间')),
                ('proposal', models.JSONField(default=dict, verbose_name='提案内容')),
                ('target_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='目标价格')),
                ('target_quantity', models.IntegerField(blank=True, null=True, verbose_name='目标数量')),
                ('target_position_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='目标仓位比例')),
                ('aggressive_view', models.TextField(verbose_name='激进派观点')),
                ('conservative_view', models.TextField(verbose_name='保守派观点')),
                ('quant_analysis', models.JSONField(default=dict, verbose_name='量化分析')),
                ('debate_summary', models.TextField(verbose_name='辩论摘要')),
                ('final_decision', models.TextField(verbose_name='最终决策')),
                ('confidence_level', models.CharField(choices=[('very_low', '很低'), ('low', '低'), ('medium', '中'), ('high', '高'), ('very_high', '很高')], max_length=20, verbose_name='置信度等级')),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='置信度分数(0-100)')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='止损价')),
                ('take_profit', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='止盈价')),
                ('max_loss_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='最大亏损金额')),
                ('is_executed', models.BooleanField(default=False, verbose_name='是否已执行')),
                ('execution_time', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('execution_result', models.JSONField(blank=True, default=dict, verbose_name='执行结果')),
                ('outcome', models.CharField(blank=True, max_length=20, null=True, verbose_name='结果')),
                ('actual_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='实际收益率')),
                ('post_analysis', models.TextField(blank=True, null=True, verbose_name='事后分析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '决策记录',
                'verbose_name_plural': '决策记录',
                'db_table': 'decision_record',
                'ordering': ['-decision_time'],
            },
        ),
        migrations.CreateModel(
            name='TradingPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('daily', '日度计划'), ('weekly', '周度计划'), ('monthly', '月度计划'), ('quarterly', '季度计划')], max_length=20, verbose_name='计划类型')),
                ('plan_date', models.DateField(db_index=True, verbose_name='计划日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '执行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('plan_data', models.JSONField(default=dict, verbose_name='计划数据')),
                ('objectives', models.JSONField(blank=True, default=list, verbose_name='目标列表')),
                ('target_symbols', models.JSONField(blank=True, default=list, verbose_name='目标标的')),
                ('risk_assessment', models.JSONField(blank=True, default=dict, verbose_name='风险评估')),
                ('expected_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='预期收益率')),
                ('max_risk_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='最大风险比例')),
                ('actual_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='实际收益率')),
                ('completion_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='完成率')),
                ('execution_summary', models.JSONField(blank=True, default=dict, verbose_name='执行摘要')),
                ('created_by', models.CharField(default='AI', max_length=50, verbose_name='创建者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '交易计划',
                'verbose_name_plural': '交易计划',
                'db_table': 'trading_plan',
                'ordering': ['-plan_date'],
                'indexes': [models.Index(fields=['plan_type', '-plan_date'], name='trading_pla_plan_ty_b9267a_idx'), models.Index(fields=['status', '-plan_date'], name='trading_pla_status_773db1_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketOpportunityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, verbose_name='标的代码')),
                ('opportunity_type', models.CharField(choices=[('breakout', '突破'), ('reversal', '反转'), ('catalyst', '催化剂'), ('valuation', '估值修复'), ('momentum', '动量'), ('sentiment', '情绪反转'), ('event', '事件驱动')], max_length=20, verbose_name='机会类型')),
                ('status', models.CharField(choices=[('identified', '已识别'), ('analyzing', '分析中'), ('validated', '已验证'), ('executed', '已执行'), ('expired', '已过期'), ('invalid', '已失效')], default='identified', max_length=20, verbose_name='状态')),
                ('identified_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='识别时间')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='有效期至')),
                ('description', models.TextField(verbose_name='描述')),
                ('rationale', models.TextField(verbose_name='依据')),
                ('expected_return', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='预期收益率')),
                ('risk_level', models.IntegerField(verbose_name='风险等级(1-10)')),
                ('trigger_conditions', models.JSONField(default=dict, verbose_name='触发条件')),
                ('entry_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='入场价格')),
                ('exit_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True, verbose_name='出场价格')),
                ('actual_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='实际收益率')),
                ('success', models.BooleanField(blank=True, null=True, verbose_name='是否成功')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='agents.decisionrecordmodel', verbose_name='相关决策')),
            ],
            options={
                'verbose_name': '市场机会',
                'verbose_name_plural': '市场机会',
                'db_table': 'market_opportunity',
                'ordering': ['-identified_at'],
            },
        ),
        migrations.AddIndex(
            model_name='decisionrecordmodel',
            index=models.Index(fields=['symbol', '-decision_time'], name='decision_re_symbol_9e466f_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionrecordmodel',
            index=models.Index(fields=['decision_type', '-decision_time'], name='decision_re_decisio_549d6f_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionrecordmodel',
            index=models.Index(fields=['is_executed', '-decision_time'], name='decision_re_is_exec_cecda0_idx'),
        ),
        migrations.AddIndex(
            model_name='marketopportunitymodel',
            index=models.Index(fields=['status', '-identified_at'], name='market_oppo_status_3c8300_idx'),
        ),
        migrations.AddIndex(
            model_name='marketopportunitymodel',
            index=models.Index(fields=['opportunity_type', '-identified_at'], name='market_oppo_opportu_2de6ed_idx'),
        ),
    ]
