# Generated by Django 4.2.26 on 2025-11-22 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='策略名称')),
                ('strategy_type', models.CharField(choices=[('trend', '趋势策略'), ('mean_reversion', '均值回归'), ('momentum', '动量策略'), ('value', '价值策略'), ('sentiment', '情绪策略'), ('hybrid', '混合策略'), ('custom', '自定义')], max_length=50, verbose_name='策略类型')),
                ('status', models.CharField(choices=[('active', '活跃'), ('testing', '测试中'), ('paused', '暂停'), ('retired', '已淘汰')], default='testing', max_length=20, verbose_name='状态')),
                ('gene_code', models.JSONField(default=dict, verbose_name='基因编码')),
                ('parameters', models.JSONField(default=dict, verbose_name='策略参数')),
                ('description', models.TextField(verbose_name='策略描述')),
                ('logic', models.TextField(verbose_name='策略逻辑')),
                ('generation', models.IntegerField(default=1, verbose_name='代数')),
                ('parent_strategies', models.JSONField(blank=True, default=list, verbose_name='父策略')),
                ('evolution_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='进化类型')),
                ('performance_metrics', models.JSONField(blank=True, default=dict, verbose_name='性能指标')),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='胜率')),
                ('profit_loss_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='盈亏比')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='夏普比率')),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='最大回撤')),
                ('total_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='总收益率')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功次数')),
                ('fail_count', models.IntegerField(default=0, verbose_name='失败次数')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='综合评分(0-100)')),
                ('last_score_update', models.DateTimeField(blank=True, null=True, verbose_name='最后评分更新时间')),
                ('market_conditions', models.JSONField(blank=True, default=dict, verbose_name='适用市场条件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('retired_at', models.DateTimeField(blank=True, null=True, verbose_name='淘汰时间')),
            ],
            options={
                'verbose_name': '交易策略',
                'verbose_name_plural': '交易策略',
                'db_table': 'strategy',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['status', '-score'], name='strategy_status_583263_idx'), models.Index(fields=['strategy_type', '-score'], name='strategy_strateg_adf768_idx')],
            },
        ),
        migrations.CreateModel(
            name='StrategyGenePoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_type', models.CharField(max_length=100, verbose_name='基因类型')),
                ('gene_name', models.CharField(max_length=200, verbose_name='基因名称')),
                ('gene_value', models.JSONField(verbose_name='基因值')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('success_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='成功率')),
                ('priority', models.IntegerField(default=50, verbose_name='优先级(0-100)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '策略基因池',
                'verbose_name_plural': '策略基因池',
                'db_table': 'strategy_gene_pool',
                'unique_together': {('gene_type', 'gene_name')},
            },
        ),
        migrations.CreateModel(
            name='StrategyEvolutionLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_strategies', models.JSONField(default=list, verbose_name='父策略列表')),
                ('evolution_type', models.CharField(choices=[('mutation', '变异'), ('crossover', '杂交'), ('natural', '自然创建'), ('manual', '人工创建')], max_length=50, verbose_name='进化类型')),
                ('evolution_details', models.JSONField(default=dict, verbose_name='进化详情')),
                ('changed_genes', models.JSONField(default=list, verbose_name='变更的基因')),
                ('trigger_reason', models.TextField(verbose_name='触发原因')),
                ('expected_improvement', models.TextField(verbose_name='预期改进')),
                ('validation_completed', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('validation_results', models.JSONField(blank=True, default=dict, verbose_name='验证结果')),
                ('is_successful', models.BooleanField(blank=True, null=True, verbose_name='是否成功')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('child_strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_logs', to='strategies.strategymodel', verbose_name='子策略')),
            ],
            options={
                'verbose_name': '策略进化日志',
                'verbose_name_plural': '策略进化日志',
                'db_table': 'strategy_evolution_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrategyBacktestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='初始资金')),
                ('symbols', models.JSONField(default=list, verbose_name='标的列表')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('final_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='最终资金')),
                ('total_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='总收益率')),
                ('annualized_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='年化收益率')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='夏普比率')),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='最大回撤')),
                ('win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='胜率')),
                ('detailed_results', models.JSONField(blank=True, default=dict, verbose_name='详细结果')),
                ('trade_records', models.JSONField(blank=True, default=list, verbose_name='交易记录')),
                ('equity_curve', models.JSONField(blank=True, default=list, verbose_name='权益曲线')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='strategies.strategymodel', verbose_name='策略')),
            ],
            options={
                'verbose_name': '策略回测',
                'verbose_name_plural': '策略回测',
                'db_table': 'strategy_backtest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['strategy', '-created_at'], name='strategy_ba_strateg_a36b84_idx'), models.Index(fields=['status', '-created_at'], name='strategy_ba_status_ed15d2_idx')],
            },
        ),
    ]
