# Generated by Django 4.2.26 on 2025-11-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSentimentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='时间戳')),
                ('vix', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='VIX指数')),
                ('fear_greed_index', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='恐慌贪婪指数')),
                ('put_call_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='看跌看涨比')),
                ('north_money_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='北向资金流入')),
                ('main_force_flow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='主力资金流入')),
                ('social_sentiment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='社交媒体情绪分数')),
                ('social_sentiment_data', models.JSONField(blank=True, default=dict, verbose_name='社交媒体情绪详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '市场情绪',
                'verbose_name_plural': '市场情绪',
                'db_table': 'market_sentiment',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StockInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='标的代码')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('market', models.CharField(max_length=20, verbose_name='市场')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='行业')),
                ('sector', models.CharField(blank=True, max_length=100, null=True, verbose_name='板块')),
                ('list_date', models.DateField(blank=True, null=True, verbose_name='上市日期')),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='市值')),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='市盈率')),
                ('pb_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='市净率')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '股票信息',
                'verbose_name_plural': '股票信息',
                'db_table': 'stock_info',
            },
        ),
        migrations.CreateModel(
            name='NewsEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('source', models.CharField(max_length=100, verbose_name='来源')),
                ('url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='链接')),
                ('published_at', models.DateTimeField(db_index=True, verbose_name='发布时间')),
                ('event_level', models.IntegerField(blank=True, choices=[(1, '低'), (2, '较低'), (3, '一般'), (4, '较高'), (5, '高'), (6, '很高'), (7, '极高'), (8, '重大'), (9, '特重大'), (10, '黑天鹅')], null=True, verbose_name='事件等级')),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='情绪分数(-100到100)')),
                ('impact_analysis', models.TextField(blank=True, null=True, verbose_name='影响分析')),
                ('related_symbols', models.JSONField(blank=True, default=list, verbose_name='相关标的')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '新闻事件',
                'verbose_name_plural': '新闻事件',
                'db_table': 'news_event',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_event_publish_80d412_idx'), models.Index(fields=['event_level', '-published_at'], name='news_event_event_l_3daeaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketIndexModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_code', models.CharField(db_index=True, max_length=50, verbose_name='指数代码')),
                ('index_name', models.CharField(max_length=100, verbose_name='指数名称')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='时间戳')),
                ('value', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='指数值')),
                ('change_pct', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='涨跌幅')),
                ('rise_count', models.IntegerField(blank=True, null=True, verbose_name='上涨家数')),
                ('fall_count', models.IntegerField(blank=True, null=True, verbose_name='下跌家数')),
                ('limit_up_count', models.IntegerField(blank=True, null=True, verbose_name='涨停家数')),
                ('limit_down_count', models.IntegerField(blank=True, null=True, verbose_name='跌停家数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '市场指数',
                'verbose_name_plural': '市场指数',
                'db_table': 'market_index',
                'ordering': ['-timestamp'],
                'unique_together': {('index_code', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='MarketDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50, verbose_name='标的代码')),
                ('market', models.CharField(choices=[('A_STOCK', 'A股'), ('US_STOCK', '美股'), ('HK_STOCK', '港股'), ('CRYPTO', '加密货币')], db_index=True, max_length=20, verbose_name='市场类型')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='时间戳')),
                ('open', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='开盘价')),
                ('high', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='最高价')),
                ('low', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='最低价')),
                ('close', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='收盘价')),
                ('volume', models.BigIntegerField(verbose_name='成交量')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True, verbose_name='成交额')),
                ('change_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='涨跌幅')),
                ('turnover_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='换手率')),
                ('data_source', models.CharField(default='unknown', max_length=50, verbose_name='数据源')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '市场行情数据',
                'verbose_name_plural': '市场行情数据',
                'db_table': 'market_data',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'market', '-timestamp'], name='market_data_symbol_8fd1c0_idx'), models.Index(fields=['market', '-timestamp'], name='market_data_market_2a7675_idx')],
                'unique_together': {('symbol', 'market', 'timestamp')},
            },
        ),
    ]
