"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import importlib
import os
from pathlib import Path
import apps

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wx&vvbdd5a+uzg0w6(k1(+sam4s5ce#l%-i7j$_==qavfaij7d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    "django_filters",
    "rest_framework.authtoken",
    "drf_yasg",
    "corsheaders",  # 添加CORS支持
    "core",
    *apps.INSTALLED_APPS,
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 添加CORS中间件
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  # REST API 不需要 CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# 根据环境变量选择数据库
DATABASE_ENGINE = os.environ.get('DATABASE_ENGINE', 'sqlite3')

if DATABASE_ENGINE == 'postgresql':
    # 生产环境使用PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DATABASE_NAME', 'datatracehub'),
            'USER': os.environ.get('DATABASE_USER', 'datatracehub'),
            'PASSWORD': os.environ.get('DATABASE_PASSWORD', ''),
            'HOST': os.environ.get('DATABASE_HOST', 'localhost'),
            'PORT': os.environ.get('DATABASE_PORT', '5432'),
            'CONN_MAX_AGE': 600,  # 数据库连接池
            'OPTIONS': {
                'connect_timeout': 10,
            }
        }
    }
else:
    # 本地开发使用SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / os.environ.get('DATABASE_NAME', 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SWAGGER_SETTINGS = {
    'PERSIST_AUTH': True,
    'REFETCH_SCHEMA_WITH_AUTH': False,
    'REFETCH_SCHEMA_ON_LOGOUT': False,

    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        },
    }
}
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        # SessionAuthentication 会强制检查 CSRF，REST API 不需要
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10
}

AWS_BUCKET_NAME = 'xxxxxxxxxxxx'
AWS_ACCESS_KEY_ID = 'xxxxxxxxxxx'
AWS_SECRET_ACCESS_KEY = 'xxxxxxxxxx'
AWS_ENDPOINT_URL = 'https://xxxxxxx.cos.ap-shanghai.myqcloud.com'
AWS_REGION_NAME = None


# CORS 配置
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = DEBUG  # 开发环境允许所有来源

# 媒体文件配置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Session配置（使用数据库存储）
SESSION_ENGINE = "django.contrib.sessions.backends.db"

# DataTraceHub 业务配置
DATATRACEHUB_CONFIG = {
    # 数据处理配置
    'BATCH_SIZE': 100,  # 批量处理事件数量
    
    # 告警配置
    'ALERT_CHECK_INTERVAL': 30,  # 告警检测间隔（秒）
    
    # 数据保留策略
    'DATA_RETENTION': {
        'raw_events': 90,  # 原始事件保留90天
        'daily_agg': 90,  # 日级聚合保留90天
        'weekly_agg': 365,  # 周级聚合保留1年
        'monthly_agg': -1,  # 月级聚合永久保留
    },
}

# 日志配置
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO')
LOG_PATH = os.environ.get('LOG_PATH', os.path.join(BASE_DIR, 'logs'))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_PATH, 'trade.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'datatracehub': {
            'handlers': ['console', 'file'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

# 创建日志目录
os.makedirs(LOG_PATH, exist_ok=True)

# AI交易系统配置
AI_TRADER_CONFIG = {
    # OpenAI配置
    'OPENAI_API_KEY': os.environ.get('OPENAI_API_KEY', ''),
    'OPENAI_BASE_URL': os.environ.get('OPENAI_BASE_URL', 'https://api.openai.com/v1'),
    'OPENAI_MODEL': os.environ.get('OPENAI_MODEL', 'gpt-4-turbo-preview'),
    'OPENAI_FAST_MODEL': os.environ.get('OPENAI_FAST_MODEL', 'gpt-3.5-turbo'),
    
    # 向量数据库配置
    'CHROMA_PERSIST_DIR': os.path.join(BASE_DIR, 'data', 'chroma_db'),
    
    # 市场数据配置
    'MARKET_DATA_DIR': os.path.join(BASE_DIR, 'data', 'market_data'),
    'ALPHAVANTAGE_API_KEY': os.environ.get('ALPHAVANTAGE_API_KEY', ''),
    'TUSHARE_TOKEN': os.environ.get('TUSHARE_TOKEN', ''),
    
    # 交易配置
    'INITIAL_CAPITAL': float(os.environ.get('INITIAL_CAPITAL', '1000000')),  # 初始资金100万
    'MAX_POSITION_PCT': float(os.environ.get('MAX_POSITION_PCT', '0.3')),  # 单标的最大仓位30%
    'MAX_SINGLE_TRADE_PCT': float(os.environ.get('MAX_SINGLE_TRADE_PCT', '0.05')),  # 单笔交易最大5%
    'STOP_LOSS_PCT': float(os.environ.get('STOP_LOSS_PCT', '0.03')),  # 默认止损3%
    'TAKE_PROFIT_PCT': float(os.environ.get('TAKE_PROFIT_PCT', '0.08')),  # 默认止盈8%
    
    # 风控配置
    'RISK_PREFERENCE': os.environ.get('RISK_PREFERENCE', 'balanced'),  # conservative/balanced/aggressive
    'MAX_DAILY_LOSS_PCT': float(os.environ.get('MAX_DAILY_LOSS_PCT', '0.05')),  # 单日最大亏损5%
    'MAX_DRAWDOWN_PCT': float(os.environ.get('MAX_DRAWDOWN_PCT', '0.15')),  # 最大回撤15%
    
    # 智能体调度配置
    'PERCEPTION_INTERVAL': int(os.environ.get('PERCEPTION_INTERVAL', '60')),  # 感知层更新间隔（秒）
    'DECISION_INTERVAL': int(os.environ.get('DECISION_INTERVAL', '300')),  # 决策层更新间隔（秒）
    'DAILY_REVIEW_TIME': os.environ.get('DAILY_REVIEW_TIME', '16:00'),  # 每日复盘时间
    'WEEKLY_REVIEW_DAY': int(os.environ.get('WEEKLY_REVIEW_DAY', '0')),  # 周度复盘日（0=周一）
    
    # 模拟交易配置
    'SIMULATION_MODE': os.environ.get('SIMULATION_MODE', 'true').lower() == 'true',
    'PARALLEL_SIMULATIONS': int(os.environ.get('PARALLEL_SIMULATIONS', '3')),  # 并行模拟盘数量
    
    # 记忆系统配置
    'MEMORY_IMPORTANCE_THRESHOLD': float(os.environ.get('MEMORY_IMPORTANCE_THRESHOLD', '5.0')),  # 记忆重要性阈值
    'MEMORY_RETENTION_DAYS': int(os.environ.get('MEMORY_RETENTION_DAYS', '90')),  # 短期记忆保留天数
}

# Redis配置（用于缓存和消息队列）
REDIS_HOST = os.environ.get('REDIS_HOST', 'localhost')
REDIS_PORT = int(os.environ.get('REDIS_PORT', '6379'))
REDIS_DB = int(os.environ.get('REDIS_DB', '0'))

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'ai_trader',
        'TIMEOUT': 300,
    }
}

# Channels配置（WebSocket）
ASGI_APPLICATION = 'core.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

# 创建必要的目录
os.makedirs(AI_TRADER_CONFIG['CHROMA_PERSIST_DIR'], exist_ok=True)
os.makedirs(AI_TRADER_CONFIG['MARKET_DATA_DIR'], exist_ok=True)

# 动态导入 config.settings 模块（仅导入特定配置，避免覆盖 REST_FRAMEWORK）
try:
    from config.settings import *
except ImportError:
    pass

# 设置自定义用户模型
AUTH_USER_MODEL = 'user.UserModel'
